//This is a menu driven program to maintain Employee Master data
import java.util.*; 
class Employee
{
  static String rec[][]=new String[10][5]; //to store employee records
  String id="",name="",age="",gender="",salary="",save="";
  int r=10,c=5,x=0,error=0;
  String ch="";int i=0,j=0,m=0,n=0,count=1;
  boolean mainflag=true,entryflag=true;
  Scanner sc= new Scanner(System.in);
  public static void main(String args[])
  {
    Employee e=new Employee();
    e.main();
  }
  
  void main() //user will choose which action to perform
  {
      while(mainflag)
      {
          heading();
          body();
          if(ch.equalsIgnoreCase("A"))  //addition of data
            dataEntry();
          if(ch.equalsIgnoreCase("U"))  //udate data
             updateEntry();
          if(ch.equalsIgnoreCase("D"))  //deletion of data
             deleteEntry();
          if(ch.equalsIgnoreCase("V"))   //view data
             viewEntry();
          if(ch.equalsIgnoreCase("S"))   //about the system
             aboutscr();
          if(ch.equalsIgnoreCase("X"))   //to exit the program
          { System.out.println('\u000C');
             mainflag=false;
          }
      }
    }
    
  void heading()  //heading
  {
      System.out.println('\u000C');
      System.out.println("--------------------------------");
      System.out.println("|  EMPLOYEE MANAGEMENT SYSTEM  |");
      System.out.println("--------------------------------");
      System.out.println( );
  }
  
  void body()  //user is given choice
  {
      System.out.println( "EMPLOYEE MASTER");
      System.out.println( );
      System.out.println( "Data Addition: A");
      System.out.println( "Data Updation: U");
      System.out.println( "Data Deletion: D");
      System.out.println( "View Records:  V");
      System.out.println( );
      System.out.println( "About System:  S");
      System.out.println( );
      System.out.println( "Exit from the system: X");
      System.out.println( );
      System.out.print("Enter your choice: ");
      ch=sc.nextLine();
  }
  
  void dataEntry()
  { 
    boolean reply=true;String choice="";
    while(reply)
    {
     heading();
     System.out.println("EMPLOYEE DETAILS (ADDITION)");
     System.out.println( );
     id="";
     if(count!= r)    //id generated by the programmer
      id=id+"0"+"0"+count; 
     else
      id=id+"0"+count; 
     System.out.println("Employee's Id         : "+id);
     System.out.println( );
     rest(); //the further data is common to both additon of data and deletion so it is kept in a function
     System.out.println( );
     System.out.print("Save the data(Y/N) ? : ");
     save=sc.nextLine();
     System.out.println( );
     System.out.print("Do you want to continue (Y/N): " );
     choice=sc.nextLine(); 
     n=0;
     if(save.equalsIgnoreCase("y"))
     {
       rec[m][n++]=id;
       rec[m][n++]=name;
       rec[m][n++]=age;
       rec[m][n++]=gender;
       rec[m][n++]=salary;
       m++;
       count++;
     }
     if(choice.equalsIgnoreCase("n"))
     reply=false;
    }
  }
  
  void rest()
  {
     System.out.print("Enter Employee's name : "); //should be max 15 characters
     name=sc.nextLine();
     if(name.length()>15) //if name"s length is >15 it will extract only 15 characters from the name
       name=name.substring(0,15);
     else
     {int sub=15-name.length();int na=1;
      while(na<=sub)  //if name"s length is < 15, it will remaining spaces(done for aligning purpose in the view part)
      {
         name=name+" ";
         na++;
      }
     }
     
     while(true) //to check whether the age is number and between 18-60 
     {System.out.print("Enter Employee's age  : ");
      age=sc.nextLine();boolean flag=true;int y=0;
      for(y=0;y<age.length();y++)
      {
          if(!Character.isDigit(age.charAt(y))) //to check if age is digit based
          {flag=false;break;}
      }
      if(flag==true)
      {
        if(Integer.valueOf(age)>17 && Integer.valueOf(age)<61)
       break;
       else
       {System.out.println( );
        System.out.println("Age should be between 18 and 60");
        System.out.println( );
       }
      }
      else
       {System.out.println( );
        System.out.println("Age should be between 18 and 60");
        System.out.println( );
      }
    }
    
    while(true) //to check gender is male or female 
     {System.out.print("Enter Gender(M/F)     : ");
      gender=sc.nextLine();
      if(gender.equalsIgnoreCase("m") || gender.equalsIgnoreCase("f"))
      break;
      else
      {System.out.println( );
        System.out.println("Wrong gender");
        System.out.println( );
      }
    }
    
    while(true) //to check salary is digit based or not
    {
     System.out.print("Enter salary          : ");
     salary=sc.nextLine();
     boolean flag=true;int y=0;
      for(y=0;y<salary.length();y++)
      {
          if(!Character.isDigit(salary.charAt(y)))
          {flag=false;break;}
      }
      if(flag==true)
      break;
      else
      {System.out.println( );
        System.out.println("Invalid salary");
        System.out.println( );
      }
    }
  }
  
  void updateEntry()  //to modify data
  {
    boolean reply=true;String choice="";
    while(reply)
    {heading();
     System.out.println("EMPLOYEE DETAILS (UPDATION)");
     System.out.println( );
     System.out.print("EMP_ID:  ");
     String newid=sc.nextLine();
     System.out.println( );
     i=0;
     while(i<10)
     { 
       if(newid.equalsIgnoreCase(rec[i][0]))  //the record of the unique id selected will be displayed
        {
         System.out.println("----------------------------------------");
         System.out.println("EMPID    NAME          AGE  GEN  SALARY");
         System.out.println("----------------------------------------");
         System.out.print(rec[i][0]+" | ");
         System.out.print(rec[i][1]+" | ");
         System.out.print(rec[i][2]+" | ");
         System.out.print(rec[i][3]+" | ");
         System.out.println(rec[i][4]+" | ");
         break;
        }
        else
        i++;
     }
     if(i>=10)
      System.out.println("** ERROR **  Invalid employee Id");
      else
      {
        System.out.println( );
        rest();  
        System.out.println( );
        System.out.print("Save the changes(Y/N) ? : ");
        save=sc.nextLine();
        System.out.println( );
        if(save.equalsIgnoreCase("y"))
        {
         if(name!="") //which field to modify
         rec[i][1]=name;
         if(age!="")
         rec[i][2]=age;
         if(gender!="")
         rec[i][3]=gender;
         if(salary!="")
         rec[i][4]=salary;
        }
      }
      System.out.println( );
      System.out.println("Do you want to continue (Y/N): " );
     choice=sc.nextLine();
     if(choice.equalsIgnoreCase("n"))
     reply=false;
    }
    }
  
  void deleteEntry()  //deletion of data
  {
    boolean reply=true;String choice="";
    while(reply)
    {heading();
     System.out.println("EMPLOYEE DETAILS (DELETION)");
     System.out.println( );
     System.out.print("EMP_ID:  ");
     String newid=sc.nextLine();
     System.out.println( );
     i=0;
     while(i<10)
     { 
       if(newid.equalsIgnoreCase(rec[i][0]))  //only records of selected id will be deleted
        {
         System.out.println("----------------------------------------");
         System.out.println("EMPID    NAME          AGE  GEN  SALARY");
         System.out.println("----------------------------------------");
         System.out.print(rec[i][0]+" | ");
         System.out.print(rec[i][1]+" | ");
         System.out.print(rec[i][2]+" | ");
         System.out.print(rec[i][3]+" | ");
         System.out.println(rec[i][4]+" | ");
         break;
        }
        else
        i++;
     }
     if(i>=10)
      System.out.println("** ERROR **  Invalid employee Id");
      else
      {
          System.out.println( );
          System.out.print("Delete this record (Y/N) ?: ");  //warning
          ch=sc.nextLine();
          if(ch.equalsIgnoreCase("y"))
          {j=0;
           while(j<5)
           {
               rec[i][j++]=null;
           }
           System.out.println( );
           System.out.println("..Record successfully deleted..");
          }
      }
     System.out.println( );
     System.out.print("Do you want to continue (Y/N): " );
     choice=sc.nextLine();
     if(choice.equalsIgnoreCase("n"))
     reply=false;
    }  
 }
 
 void viewEntry()  //view the records
  {
    boolean reply=true;String choice="";
    while(reply)
    {heading();
     System.out.println("        EMPLOYEE RECORDS       ");
     System.out.println( );
     System.out.println("----------------------------------------");
     System.out.println("EMPID    NAME          AGE  GEN  SALARY");
     System.out.println("----------------------------------------");
     for(i=0;i<r;i++)
     {
         for(j=0;j<c;j++)
         {
             if(rec[i][j]!=null)
             System.out.print(rec[i][j]+" | ");
         }
         if(rec[i][0]!=null)
         System.out.println( );
     }
     System.out.println( );
     System.out.println("Do you want to continue (Y/N): " );
     choice=sc.nextLine();
     if(choice.equalsIgnoreCase("n"))
     reply=false;
    }
  }
  
  void aboutscr()
  {
      String choice="";
      heading();
      System.out.println("** IMPORTANT NOTES REGARDING SYSTEM **" );
      System.out.println( );
      System.out.println("This is a menu driven program where there is only one entry and exit point");
      System.out.println("Data is stored in array hence all data will be removed from the memory on exit");
      System.out.println("Employee Id is system generated");
      System.out.println("Employee name should be maximum of 15 characters long");
      System.out.println("Employee age should be between 18 to 60");
      System.out.println("Employee gender should be either male or female");
      System.out.println("Enter only M or F");
      System.out.println("Employee salary should not be negative");
      System.out.println( );
      System.out.println("********************************************************");
      System.out.println( );
      System.out.println("Press any key to back" );
      choice=sc.nextLine();
  }
}

